name: Build and Push Auth Service Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: mx-queretaro-1.ocir.io
      NAMESPACE: axfvmmw9g9lu
      REPOSITORY: taskmanager
      IMAGE_NAME: task-service
      VERSION: 3 #Cambiar siempre que se haga un push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Recreate wallet files from secrets
        run: |
          # Crear el directorio de wallet
          mkdir -p wallet
          
          # Decodificar los secretos y crear los archivos
          echo "${{ secrets.WALLET_CWALLET_SSO }}" | base64 -d > wallet/cwallet.sso
          echo "${{ secrets.WALLET_TNSNAMES_ORA }}" | base64 -d > wallet/tnsnames.ora
          echo "${{ secrets.WALLET_SQLNET_ORA }}" | base64 -d > wallet/sqlnet.ora
          echo "${{ secrets.WALLET_EWALLET_P12 }}" | base64 -d > wallet/ewallet.p12
          echo "${{ secrets.WALLET_KEYSTORE_JKS }}" | base64 -d > wallet/keystore.jks
          echo "${{ secrets.WALLET_OJDBC_PROPERTIES }}" | base64 -d > wallet/ojdbc.properties
          echo "${{ secrets.WALLET_EWALLET_PEM }}" | base64 -d > wallet/ewallet.pem
          echo "${{ secrets.WALLET_README }}" | base64 -d > wallet/README
          echo "${{ secrets.WALLET_TRUSTSTORE_JKS }}" | base64 -d > wallet/truststore.jks
          
          # Establecer permisos correctos
          chmod 600 wallet/*
          
          # Verificar la creación de los archivos
          ls -la wallet/

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Cambia a '23' si estás usando JDK 23
          distribution: 'temurin'
          cache: maven

      - name: Modify application.properties
        run: |
          sed -i 's|TNS_ADMIN=C:/Users/cesar/Wallet_TelegramBotDatabase|TNS_ADMIN=/wallet|g' src/main/resources/application.properties
          # Verificar el cambio
          cat src/main/resources/application.properties

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      # Movemos el JAR a una ubicación donde el Dockerfile pueda acceder
      - name: Prepare for Docker build
        run: |
          mkdir -p build
          
          # Verificar contenido del directorio target
          echo "Contenido del directorio target:"
          ls -la target/
          
          # Comprobamos si el JAR existe
          if [ ! -f "target/TaskService-0.0.1-SNAPSHOT.jar" ]; then
            echo "ERROR: El archivo JAR no existe en target/"
            exit 1
          fi
          
          cp target/TaskService-0.0.1-SNAPSHOT.jar build/
          # Copiamos el wallet
          mkdir -p build/wallet
          cp -r wallet/* build/wallet/
          
          # Crear un Dockerfile temporal que podamos usar en el contexto del repositorio
          cat > Dockerfile << EOF
          FROM eclipse-temurin:23-jre

          # Directorio de trabajo en el contenedor
          WORKDIR /TaskService
          
          # Creamos un directorio vacío para el wallet que se montará después
          RUN mkdir -p /wallet

          # Copiar el archivo JAR al contenedor
          COPY build/TaskService-0.0.1-SNAPSHOT.jar TaskService.jar
          
          # Copiar el wallet al contenedor
          COPY build/wallet /wallet/
          
          # Exponer el puerto 8080
          EXPOSE 8081

          # Establecer la variable de entorno TNS_ADMIN
          ENV TNS_ADMIN=/wallet
          ENV ORACLE_HOME=/wallet
          ENV LD_LIBRARY_PATH=/wallet
          
          # Mostrar el contenido del directorio /wallet
          RUN ls -la /wallet

          # Ejecutar la aplicación con la propiedad del sistema oracle.net.tns_admin
          ENTRYPOINT ["java", "-jar", "TaskService.jar"]
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Oracle Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.NAMESPACE }}/${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Build and Push Docker image
        run: |
          #Construir la imagen
          docker build -t ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:v${{ env.VERSION }} -f Dockerfile .
          
          # Subir solo el tag
            docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:v${{ env.VERSION }}

      - name: Print image details
        run: |
          echo "============================================"
          echo "Image successfully built and pushed!"
          echo "Image: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:v${{ env.VERSION }}"
          echo "============================================"
          echo "To update your Kubernetes deployment, run:"
          echo "kubectl set image deployment/task-service task-service=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:v${{ env.VERSION }}"
          echo "============================================"